import Head from 'next/head'
import Link from 'next/link'
import { useEffect } from 'react'
// import styles from '../styles/Home.module.css'


import { useRouter } from "next/router";
import Navbar from '@/app/components/home/navbar';

export default function Home(props) {
  const router = useRouter()

  return (
    <div>
      <Head>
        <title></title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="true" />
        <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@100;200;300;400;500;600;700;800;900&display=swap" rel="stylesheet" />
      </Head>
      <main>
        <Navbar></Navbar>
      </main>

    </div>
  )
}
